# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G_szFwPzFPoC72crI20x4AFrYLxVJRg4
"""

! pip install -q https://github.com/pandas-profiling/pandas-profiling/archive/master.zip

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
from pandas_profiling import ProfileReport

accident = pd.read_csv('/content/Accidents.csv')
biker = pd.read_csv('/content/Accidents.csv')

accident.head()

biker.head()

df = accident.merge(biker, on='Accident_Index', how='left')

df.head()

ProfileReport(df, title="Bicycle Accident", explorative=True)